# Generated by Django 5.0.6 on 2024-05-31 05:50

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('JobTitle', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(blank=True, default=None, null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Body')),
                ('is_published', models.BooleanField(default=False)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('read_time', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.author')),
                ('post_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.posttag')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.posttype')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogPost1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_blog_post_1', to='posts.post')),
                ('BlogPost2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_blog_post_2', to='posts.post')),
                ('BlogPost3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_blog_post_3', to='posts.post')),
                ('BlogPost4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_blog_post_4', to='posts.post')),
            ],
        ),
    ]
