# Generated by Django 5.0.6 on 2024-05-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_summary',
            field=models.CharField(blank=True, help_text='A brief summary describing the content in 255 characters or less.', max_length=255, null=True),
        ),
    ]
