# Generated by Django 5.0.6 on 2024-05-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_short_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': '1. Authors'},
        ),
        migrations.AlterModelOptions(
            name='featuredblogs',
            options={'verbose_name': 'Featured Blogs', 'verbose_name_plural': '5. Featured Blogs'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Posts', 'verbose_name_plural': '4. Posts'},
        ),
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'Post Tag', 'verbose_name_plural': '3. Post Tags'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'verbose_name': 'Post Type', 'verbose_name_plural': '2. Post Types'},
        ),
    ]
