# Generated by Django 5.0.6 on 2024-06-03 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_author_uuid_post_uuid_posttag_uuid_posttype_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredblogs",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
