# Generated by Django 5.0.6 on 2024-05-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectUs',
            new_name='ContactUs',
        ),
    ]
