# Generated by Django 5.0.6 on 2024-05-31 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_connectus_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurInitiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('PioneeringProjects_title', models.TextField(blank=True, null=True)),
                ('FoundedYear', models.IntegerField()),
                ('Projects', models.IntegerField()),
                ('Communitites', models.CharField(blank=True, max_length=255, null=True)),
                ('Volunteers', models.CharField(blank=True, max_length=255, null=True)),
                ('BannerImage', models.ImageField(blank=True, default=None, null=True, upload_to='banners/OurInitiatives', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('box_title1', models.CharField(blank=True, max_length=255, null=True)),
                ('box_text1', models.TextField(blank=True, null=True)),
                ('box_icon1', models.ImageField(blank=True, default=None, null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('box_title2', models.CharField(blank=True, max_length=255, null=True)),
                ('box_text2', models.TextField(blank=True, null=True)),
                ('box_icon2', models.ImageField(blank=True, default=None, null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('box_title3', models.CharField(blank=True, max_length=255, null=True)),
                ('box_text3', models.TextField(blank=True, null=True)),
                ('box_icon3', models.ImageField(blank=True, default=None, null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
    ]
