# Generated by Django 5.0.6 on 2024-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_introduction_ourinitiatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
