# Generated by Django 5.0.6 on 2024-05-31 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_boardofdirector_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(choices=[('Privacy Policy', 'Privacy Policy'), ('Terms and Conditions', 'Terms of Service')], max_length=255)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('about', 'About HCG'), ('mission', 'Mission and Vision'), ('Introduction', 'Introduction')], max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
