# Generated by Django 5.0.6 on 2024-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_files_page_delete_introduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardofdirector',
            options={'verbose_name': 'Board of Directors', 'verbose_name_plural': '1. Board of Directors'},
        ),
        migrations.AlterModelOptions(
            name='contacthcg',
            options={'verbose_name': 'Contact HCG Information', 'verbose_name_plural': '4. Contact HCG Information'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': '5. Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': '9.1 Files'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyaskedquestions',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': '7. FAQS'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'News letter', 'verbose_name_plural': '6. News letters'},
        ),
        migrations.AlterModelOptions(
            name='ourinitiatives',
            options={'verbose_name': 'Our Inititatives', 'verbose_name_plural': '3. Our Inititatives'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': '9. Pages'},
        ),
        migrations.AlterModelOptions(
            name='socialmediaurl',
            options={'verbose_name': 'Social Media URL', 'verbose_name_plural': '8. Social Media URL'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Teams', 'verbose_name_plural': '2. Teams'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
