# Generated by Django 5.0.6 on 2024-06-03 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_boardofdirector_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="designations",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("Is_Board_Member", models.BooleanField(default=False)),
                ("Is_Teams", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Designation",
                "verbose_name_plural": "1. Designations",
            },
        ),
        migrations.DeleteModel(
            name="BoardOfDirector",
        ),
        migrations.DeleteModel(
            name="Teams",
        ),
        migrations.AlterModelOptions(
            name="contacthcg",
            options={
                "verbose_name": "Contact HCG Information",
                "verbose_name_plural": "3. Contact HCG Information",
            },
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "4. Contact Us",
            },
        ),
        migrations.AlterModelOptions(
            name="files",
            options={"verbose_name": "File", "verbose_name_plural": "9 Files"},
        ),
        migrations.AlterModelOptions(
            name="frequentlyaskedquestions",
            options={"verbose_name": "FAQ", "verbose_name_plural": "6. FAQS"},
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "verbose_name": "News letter",
                "verbose_name_plural": "5. News letters",
            },
        ),
        migrations.AlterModelOptions(
            name="ourinitiatives",
            options={
                "verbose_name": "Our Inititatives",
                "verbose_name_plural": "2. Our Inititatives",
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "Page", "verbose_name_plural": "8. Pages"},
        ),
        migrations.AlterModelOptions(
            name="socialmediaurl",
            options={
                "verbose_name": "Social Media URL",
                "verbose_name_plural": "7. Social Media URL",
            },
        ),
    ]
