# Generated by Django 5.0.6 on 2024-06-03 05:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_contacthcg_uuid_designation_uuid_files_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
