# Generated by Django 5.0.6 on 2024-05-31 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_jobopening_jobrequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('CV', models.FileField(blank=True, default=None, null=True, upload_to='CVs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.jobopening')),
            ],
        ),
    ]
