# Generated by Django 5.0.6 on 2024-05-31 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_candidate_created_at_candidate_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectFile', models.FileField(blank=True, default=None, null=True, upload_to='CVs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
