# Generated by Django 5.0.6 on 2024-05-31 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='ProjectFile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Proposals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
