# Generated by Django 5.0.6 on 2024-06-03 03:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0007_alter_candidate_options_alter_jobopening_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="jobtype",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="proposal",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
